---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: internaltableau
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: internaltableau
    spec:
      containers:
        - name: opensslsidekick
          image: quay.io/ukhomeofficedigital/dq-haproxy-openssl-sidekick:b489e4b631ebddf4513ca536b01e2cd80af60f6d
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
          env:
            - name: EXPOSED_PORT
              value: '5000'
            - name: HOST
              value: '10.3.0.11'
            - name: PORT
              value: '8081'
          ports:
            - containerPort: 5000

        - name: proxy
          image: quay.io/ukhomeofficedigital/nginx-proxy-proxy-redirect
          securityContext:
            runAsNonRoot: true
          env:
            - name: PROXY_SERVICE_HOST
              value: 'https://10.3.0.11'
            - name: PROXY_SERVICE_PORT
              value: '8081'
            - name: LOG_FORMAT_NAME
              value: 'json'
            - name: NAXSI_USE_DEFAULT_RULES
              value: 'FALSE'
            - name: ENABLE_UUID_PARAM
              value: 'FALSE'
            - name: ADD_NGINX_SERVER_CFG
              value: |
                proxy_read_timeout 300s;
                proxy_send_timeout 300s;
                proxy_connect_timeout 300s;
                proxy_set_header  X-Real-IP $remote_addr;
                proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header  X-Forwarded-Host $server_name;
                proxy_set_header  X-Forwarded-Proto https;
                proxy_redirect https://analysis.prod.dq.homeoffice.gov.uk:10443/ https://analysis.prod.dq.homeoffice.gov.uk/;
          ports:
            - name: https
              containerPort: 10443
